# **Prepare a classification model using SVM for salary data (SalaryData_Test(1))**

# Import data and models

In [41]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.metrics import accuracy_score,confusion_matrix

In [42]:
data = pd.read_csv('SalaryData_Test(1).csv')
data.head(10)

age          workclass      education  educationno        maritalstatus  \
0   25            Private           11th            7        Never-married   
1   38            Private        HS-grad            9   Married-civ-spouse   
2   28          Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44            Private   Some-college           10   Married-civ-spouse   
4   34            Private           10th            6        Never-married   
5   63   Self-emp-not-inc    Prof-school           15   Married-civ-spouse   
6   24            Private   Some-college           10        Never-married   
7   55            Private        7th-8th            4   Married-civ-spouse   
8   65            Private        HS-grad            9   Married-civ-spouse   
9   36        Federal-gov      Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black     Male            0   
1     Farming-fishing         Husband   White     Male            0   
2     Protective-serv         Husband   White     Male            0   
3   Machine-op-inspct         Husband   Black     Male         7688   
4       Other-service   Not-in-family   White     Male            0   
5      Prof-specialty         Husband   White     Male         3103   
6       Other-service       Unmarried   White   Female            0   
7        Craft-repair         Husband   White     Male            0   
8   Machine-op-inspct         Husband   White     Male         6418   
9        Adm-clerical         Husband   White     Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K  
5            0            32   United-States    >50K  
6            0            40   United-States   <=50K  
7            0            10   United-States   <=50K  
8            0            40   United-States    >50K  
9            0            40   United-States   <=50K

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            15060 non-null  int64 
 1   workclass      15060 non-null  object
 2   education      15060 non-null  object
 3   educationno    15060 non-null  int64 
 4   maritalstatus  15060 non-null  object
 5   occupation     15060 non-null  object
 6   relationship   15060 non-null  object
 7   race           15060 non-null  object
 8   sex            15060 non-null  object
 9   capitalgain    15060 non-null  int64 
 10  capitalloss    15060 non-null  int64 
 11  hoursperweek   15060 non-null  int64 
 12  native         15060 non-null  object
 13  Salary         15060 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.6+ MB


In [5]:
data['workclass'] = data['workclass'].astype('category')
data['education'] = data['education'].astype('category')
data['maritalstatus'] = data['maritalstatus'].astype('category')
data['occupation'] = data['occupation'].astype('category')
data['relationship'] = data['relationship'].astype('category')
data['race'] = data['race'].astype('category')
data['sex'] = data['sex'].astype('category')
data['native'] = data['native'].astype('category')
data['Salary'] = data['Salary'].astype('category')

In [6]:
data.dtypes

age                 int64
workclass        category
education        category
educationno         int64
maritalstatus    category
occupation       category
relationship     category
race             category
sex              category
capitalgain         int64
capitalloss         int64
hoursperweek        int64
native           category
Salary           category
dtype: object

In [7]:
data['Salary'] = data['Salary'].cat.codes
data.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States       0  
1            0            50   United-States       0  
2            0            40   United-States       1  
3            0            40   United-States       1  
4            0            30   United-States       0

# will use the Age and Hoursperweek only for this Analysis

In [8]:
data1 = data.iloc[:,[0,11,13]]
data1.head()

age  hoursperweek  Salary
0   25            40       0
1   38            50       0
2   28            40       1
3   44            40       1
4   34            30       0

In [9]:
x = data1.iloc[:,0:2]

In [10]:
print(x)

       age  hoursperweek
0       25            40
1       38            50
2       28            40
3       44            40
4       34            30
...    ...           ...
15055   33            40
15056   39            36
15057   38            50
15058   44            40
15059   35            60

[15060 rows x 2 columns]


In [11]:
y = data1.iloc[:,-1]
print(y.head())

0    0
1    0
2    1
3    1
4    0
Name: Salary, dtype: int8


# print the unique labels of the dataset

In [12]:
np.unique(y)

array([0, 1], dtype=int8)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = .3,random_state = 0)

In [15]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((10542, 2), (10542,), (4518, 2), (4518,))

In [16]:
from sklearn.svm import SVC

In [17]:
svm = SVC(kernel = 'rbf', gamma = .10, C = 1.0)

In [18]:
svm.fit(x_train,y_train)

SVC(gamma=0.1)

# The accuracy of the sum classifire on the training data

In [19]:
svm.score(x_train,y_train)

0.7705369000189717

# The accuracy of the classifire on the test data

In [20]:
svm.score(x_test,y_test)

0.7532093846834883

In [21]:
clf = SVC(C= 1.5, gamma = .50)
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 74.9003984063745


array([[3192,  193],
       [ 941,  192]], dtype=int64)

# Prepare a model using SVM for salary data (SalaryData_Train(2))

In [22]:
data2 = pd.read_csv('SalaryData_Train(1).csv')

In [23]:
data2.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [24]:
data2.dtypes

age               int64
workclass        object
education        object
educationno       int64
maritalstatus    object
occupation       object
relationship     object
race             object
sex              object
capitalgain       int64
capitalloss       int64
hoursperweek      int64
native           object
Salary           object
dtype: object

In [25]:
data2['workclass'] = data2['workclass'].astype('category')
data2['education'] = data2['education'].astype('category')
data2['maritalstatus'] = data2['maritalstatus'].astype('category')
data2['occupation'] = data2['occupation'].astype('category')
data2['relationship'] = data2['relationship'].astype('category')
data2['race'] = data2['race'].astype('category')
data2['sex'] = data2['sex'].astype('category')
data2['native'] = data2['native'].astype('category')
data2['Salary'] = data2['Salary'].astype('category')

In [26]:
data2['Salary'] = data2['Salary'].cat.codes

In [27]:
data3 = data2.iloc[:,[0,11,13]]

In [28]:
data3.head()

age  hoursperweek  Salary
0   39            40       0
1   50            13       0
2   38            40       0
3   53            40       0
4   28            40       0

In [29]:
X = data3.iloc[:,0:2]
Y = data3.iloc[:,2]

In [30]:
print(X.head())

   age  hoursperweek
0   39            40
1   50            13
2   38            40
3   53            40
4   28            40


In [31]:
print(Y.head())

0    0
1    0
2    0
3    0
4    0
Name: Salary, dtype: int8


In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = .4, random_state= 0)

In [34]:
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((18096, 2), (18096,), (12065, 2), (12065,))

# support vector Machine

In [36]:
cv = SVC(kernel = 'rbf', random_state = 0, gamma = .10, C = 1.0 )

In [37]:
cv.fit(X_train,Y_train)

SVC(gamma=0.1, random_state=0)

# Accuracy of the sum classifire on the training data

In [38]:
cv.score(x_train,y_train)

0.7557389489660405

# The accuracy of the classifire on the test data

In [39]:
cv.score(x_test,y_test)

0.7565294378043382

In [40]:
clf = SVC(C= 1.5, gamma = .15)
clf.fit(X_train , Y_train)
Y_pred = clf.predict(X_test)
acc = accuracy_score(Y_test, Y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(Y_test, Y_pred)

Accuracy = 76.14587650227932


array([[8549,  512],
       [2366,  638]], dtype=int64)